# Generated by Django 2.2.5 on 2019-10-07 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Info_name', models.CharField(max_length=100)),
                ('Info_desc', models.CharField(max_length=100)),
            ],
        ),
    ]
