# Generated by Django 2.2.6 on 2019-10-08 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0005_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work_Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.CharField(max_length=20)),
                ('Name', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=150)),
            ],
        ),
    ]
